server:
  port: 7071

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abhishekpanda890@gmail.com
    password: onqdiftphczjuijy
    properties:
      mail:
      smtp:
      auth: true
      starttls:
      enable: true
      required: true

  datasource:
    url: jdbc:mysql://localhost:3306/admin_api
    username: root
    password: Iopjkl@890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


  application:
    name: ADMIN-API

  boot:
    admin:
      client:
        url: http://localhost:6081

  cloud:
    compatibility-verifier:
      enabled: false


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:7090/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

